version: "3"
services:
  api:
    build: .
    container_name: api
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./rinha_de_backend/:/app
    networks:
      - app-network
    env_file:
      - .env

  db:
    image: postgres:15.0-alpine
    container_name: db
    restart: unless-stopped
    volumes:
      - ./temp/:/var/lib/postgresql/data
    ports:
      - 5432:${POSTGRES_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge